services:
  registrologin-db:
    image: mysql:8.0
    container_name: registrologin-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?Define DB_ROOT_PASSWORD en .env}
      MYSQL_DATABASE: ${DB_NAME:?Define DB_NAME en .env}
      MYSQL_USER: ${DB_USER:?Define DB_USER en .env}
      MYSQL_PASSWORD: ${DB_PASSWORD:?Define DB_PASSWORD en .env}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
